"""Update products table

Revision ID: d24c3499da96
Revises: 50a439e81e71
Create Date: 2024-11-02 10:01:31.950120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd24c3499da96'
down_revision: Union[str, None] = '50a439e81e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sale_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SOLD_OUT', 'DELETED', name='productstatus'), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('category', sa.String(length=50), nullable=True))
    op.alter_column('products', 'name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.alter_column('products', 'description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.drop_column('products', 'category')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'status')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'sale_price')
    # ### end Alembic commands ###
